project:
  type: website
  output-dir: docs
  preview:
    port: 5896
    browser: true
  render:
    - "*.qmd"
  resources:
    - "showcase/"
    - "CNAME"

website:
  title: Exploratory Data Analysis
  site-url: https://eda.seas.gwu.edu/
  favicon: images/favicon.ico
  repo-url: https://github.com/emse-eda-gwu/
  description: 'Course website for the EMSE course "Exploratory Data Analysis" at GWU'
  search: true
  open-graph:
    locale: es_ES
    site-name: https://eda.seas.gwu.edu/
  twitter-card:
    creator: "@johnhelveston"
    site: "@johnhelveston"
    image: "images/logo_square.png"
    card-style: summary
  navbar:
    title: ""
    left:
      - text: "Select Section"
        menu:
          - text: "Spring 2020"
            href: http://eda.seas.gwu.edu/2020-Spring/
          - text: "Spring 2021"
            href: http://eda.seas.gwu.edu/2021-Spring/
          - text: "Fall 2022"
            href: http://eda.seas.gwu.edu/2022-Fall/
          - text: "Fall 2023"
            href: http://eda.seas.gwu.edu/2023-Fall/
          - text: "Fall 2024"
            href: http://eda.seas.gwu.edu/2024-Fall/
      - text: "Project Showcase"
        href: showcase.qmd
    right:
    - icon: list
      menu:
      - text: About
        icon: question-circle-fill
        href: about.qmd
      - text: License
        icon: award-fill
        href: LICENSE.qmd
      - text: Contact
        icon: envelope-fill
        href: mailto:jph@gwu.edu
      - text: Source files
        icon: github
        href: https://github.com/emse-eda-gwu/
  page-footer:
    center:
      - text: "<a href='https://eda.seas.gwu.edu/LICENSE.html'>LICENSE: CC-BY-SA {{< fa creative-commons-sa >}} <i class='fab fa-creative-commons'></i><i class='fab fa-creative-commons-by'></i><i class='fab fa-creative-commons-sa'></i></a>"

format:
  html:
    theme: cyborg
    css: styles.css
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false

execute: 
  echo: false
  warning: false
  message: false
knitr:
  opts_chunk:
    comment: "#>"
fig-retina: 3
toc: true
toc-location: right