project:
  type: website
  output-dir: _site
  preview:
    port: 5896
    browser: true
  render:
    - "*.qmd"
  resources:
    - "showcase/"

website:
  title: "PUBH6199: Visualizing Data with R"
  site-url: https://pubh6199-data-viz-with-r.github.io/
  favicon: images/favicon.ico
  repo-url: https://github.com/pubh6199-data-viz-with-r
  description: 'Course website for the graduate-level course "PUBH 6199: Visualizing Data with R" at GWU'
  search: true
  open-graph:
    locale: es_ES
    site-name: https://pubh6199-data-viz-with-r.github.io/
  navbar:
    title: ""
    left:
      - text: "Select Section"
        menu:
          - text: "Summer 2025"
            href: https://pubh6199-data-viz-with-r.github.io/2025-Summer/
      - text: "Project Showcase"
        href: showcase.qmd
    right:
    - icon: list
      menu:
      - text: About
        icon: question-circle-fill
        href: about.qmd
      - text: License
        icon: award-fill
        href: LICENSE.qmd
      - text: Contact
        icon: envelope-fill
        href: mailto:xindi.hu@gwu.edu
      - text: Source files
        icon: github
        href: https://github.com/pubh6199-data-viz-with-r
  page-footer:
    left: "© 2025 Dr. Xindi Hu"
    center:
      - text: "<a href='https://pubh6199-data-viz-with-r.github.io/LICENSE.html'>LICENSE: CC-BY-SA <i class='fab fa-creative-commons'></i><i class='fab fa-creative-commons-by'></i><i class='fab fa-creative-commons-sa'></i></a>"
    right: "GWU Milken Institute SPH"
format:
  html:
    theme: flatly
    css: styles.css
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false

execute: 
  echo: false
  warning: false
  message: false
knitr:
  opts_chunk:
    comment: "#>"
fig-retina: 3
toc: true
toc-location: right